
spring:
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: ''
    # 连接超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000ms
    #哨兵配置
    sentinel:
      master: mymaster
      nodes: 192.168.88.132:26379,192.168.88.132:26380,192.168.88.132:26381
      password: 123456